---
__php_packages:
  - php7.0-common
  - php7.0-cli
  - php7.0-dev
  - php7.0-fpm
  - libpcre3-dev
  - php7.0-gd
  - php7.0-curl
  - php7.0-imap
  - php7.0-json
  - php7.0-opcache
  - php7.0-xml
  - php7.0-mbstring
  - php-sqlite3
  - php-apcu
  - php7.0-cgi
  - php7.0-intl
  - php7.0-odbc
  - php7.0-tidy
  - php7.0-xmlrpc
  - php-pear
  - php7.0-mcrypt
  - php7.0-mysqlnd
  - php7.0-imagick
  - php7.0-zip

__php_webserver_daemon: "nginx"

# Vendor-specific configuration paths on Debian/Ubuntu make my brain asplode.
__php_conf_paths:
  - /etc/php/7.0/fpm
  - /etc/php/7.0/apache2
  - /etc/php/7.0/nginx
  - /etc/php/7.0/cli

__php_extension_conf_paths:
  - /etc/php/7.0/fpm/conf.d
  - /etc/php/7.0/apache2/conf.d
  - /etc/php/7.0/nginx/conf.d
  - /etc/php/7.0/cli/conf.d

__php_apc_conf_filename: 20-apcu.ini
__php_opcache_conf_filename: 05-opcache.ini
__php_fpm_daemon: php7.0-fpm
__php_fpm_conf_path: "/etc/php/7.0/fpm"
__php_fpm_pool_conf_path: "{{ __php_fpm_conf_path }}/pool.d/www.conf"

__php_fpm_pool_user: www-data
__php_fpm_pool_group: www-data
